### ISSUE TITLE
[i18n] Translate UI into multiple languages.

### ISSUE THREAD

**Issue by junderw** [getumbrel/umbrel#489] opened 2021-02-07 09:12 UTC
I call dibs on Japanese.

We can use Transifex etc. to gather translations from volunteers.

**Comment by lukechilds** [comment] 2021-02-07 09:19
Awesome, thanks @junderw!

We aren't quite ready to implement it yet since there'll be a lot of churn during beta and it'll probably introduce too much overhead.

But it's definitely on the post stable release todo list!

Gonna close this issue as a dupe of https://github.com/getumbrel/umbrel-dashboard/issues/212 but feel free to call your dibs over there!

**Closed by lukechilds** 2021-02-07 09:19 UTC
