### ISSUE TITLE
Web syslog viewing breaks after log rotation

### ISSUE THREAD

**Issue by dcninja** [getumbrel/umbrel#575] opened 2021-02-26 16:16 UTC
Accessing the logs via webbrowser at xxx.xxx.xxx.xxx/logs normally results in stream of syslog. However it seems that after midnight when the logs rotate, this webpage no longer updates, example output below

> Feb 24 23:58:03 umbrel bitcoin[752]: 2021-02-24T23:58:03Z FlushStateToDisk: write coins cache to disk (22417883 coins, 3179741kB) started
>Feb 24 23:59:03 umbrel umbrel-app mempool_api_1[752]: Feb 24 23:59:03 [38] WARN: runMainLoop error: ETIMEDOUT. Retrying in 60 sec.
>Feb 24 23:59:03 umbrel umbrel-app mempool_api_1[752]: Feb 24 23:59:03 [38] DEBUG: {"code":"ETIMEDOUT"}
>Feb 25 00:00:41 umbrel systemd[1]: Starting Daily man-db regeneration...
>Feb 25 00:00:41 umbrel systemd[1]: Starting Rotate log files... 

Checking tail -f /var/log/syslog via SSH shows logs still incoming. 

Running 0.3.5 on RaspPi8GB

**Comment by AaronDewes** [comment] 2021-02-26 16:18
Duplicate of https://github.com/getumbrel/umbrel/issues/361.

**Closed** 2021-03-06 10:01 UTC
