### ISSUE TITLE
Can't expose Mempool anymore because of signin page

### ISSUE THREAD

**Issue by jameskitt616** [getumbrel/umbrel#1420] opened 2022-06-08 06:31 UTC
Hey there,
i used to expose the mempool app to public for anyone to use it via reverse proxy, but due the latest update (v0.5.0) this is not possible anymore. It always redirects to the login page of umbrel to sign in. This does not make much sense and there should be a way to disable this either for single apps or entirely.

**Comment by nevets963** [comment] 2022-06-08 10:48
This is a duplicate of this issue: https://github.com/getumbrel/umbrel/issues/1412

Within there I've provided instructions so you can remove the authenticaton :)

**Closed by nevets963** 2022-06-08 10:48 UTC
