### ISSUE TITLE
RTL installation fails silently

### ISSUE THREAD

**Issue by thelwyn** [getumbrel/umbrel#494] opened 2021-02-09 01:56 UTC
I've tried multiple time to install RTL on my Umbrel, it never worked. It shows "Installing..." forever. OTOH I could install the BTC RPC Explorer without any problem.

Debug log:
https://pastebin.com/r4Pkycir

@saubyk The first time I tried to install I waited like 4h, since nothing was happening I tried to reboot (using the restart button in Settings interface), my Umbrel then became unreachable from Web. 

The original log was this one: https://pastebin.com/gnJatWcy

Aaron let me enter this command from ssh: sudo ~/umbrel/scripts/app uninstall ride-the-lightning  and my umbrel came back to life. He said I shouldn't have to reboot during an install... but what if the install is not going on and you're suggested to reboot? :D

Since then I've tried at least 3 times to install, it says "Installing..." but nothing ever happen and if I come back way later to the apps page -> RTL , it justs dispay the "Install" button again, like nothing happened. So it just fails silently.

**Comment by saubyk** [comment] 2021-02-09 02:09
This seems to be the issue:
```
Starting app ride-the-lightning...
Creating ride-the-lightning_loop_1 ...
Creating ride-the-lightning_web_1  ...
Creating ride-the-lightning_loop_1 ... error
Creating ride-the-lightning_web_1  ... error
 
Creating ride-the-lightning_loop_1 ... done
fa0e200885fada7bbd79efc2f238e54be057f1ff1ec13a88d1e67b16e7e919d". You have to remove (or rename) that container to be able to reuse that name.
 
ERROR: for web  Cannot create container for service web: Conflict. The container name "/ride-the-lightning_web_1" is already in use by container "bfa0e200885fada7bbd79efc2f238e54be057f1ff1ec13a88d1e67b16e7e919d". You have to remove (or rename) that container to be able to reuse that name.
Encountered errors while bringing up the project.
 
ERROR: for ride-the-lightning_loop_1  Cannot create container for service loop: Conflict. The container name "/ride-the-lightning_loop_1" is already in use by containerCreating ride-the-lightning_web_1  ... done
 
ERROR: for loop  Cannot create container for service loop: Conflict. The container name "/ride-the-lightning_loop_1" is already in use by container "a67380aafba5d4c4c2eb46f5ab68c5897068d2ae832b9c341bcb32bb8647d80e". You have to remove (or rename) that container to be able to reuse that name.
Encountered errors while bringing up the project.
Got signal: reboot
karen is getting triggered!
Stopping installed apps...
```

This can best be debugged by @lukechilds or @louneskmt 
Appears to be docker specific rather than anything related to the application. We can investigated further based on their guidance.

**Comment by thelwyn** [comment] 2021-02-09 02:29
However this error might have showed up when I try to install the second time (like after 4h nothing happened, open the "apps" page again and try install RTL again. This log looks like something like this no? conflict between 2 RTL at same time?

**Comment by louneskmt** [comment] 2021-02-09 07:20
Can you try to uninstall and install the app manually? To check if the issue is the app itself or the installation process via the UI. 

```
~/umbrel/scripts/app uninstall ride-the-lightning
```

Then
```
~/umbrel/scripts/app install ride-the-lightning
```

**Comment by thelwyn** [comment] 2021-02-09 14:28
We're getting there: https://pastebin.com/cjiGqhWF
Permission denied. I tried again, sudoing my way this time and RTL installed instantly.

**Comment by thelwyn** [comment] 2021-02-09 15:01
Same problem with BTCPay-server (/home/umbrel/umbrel/scripts/app: line 106: /home/umbrel/umbrel/db/user.json: Permission denied
), it only installs by executing the install with sudo. From the Web GUI it justs fails silently as RTL.
Specter and the RPC Explorer installed fine on the other hand without any sudo.

**Comment by AaronDewes** [comment] 2021-02-09 18:08
Are you using Umbrel OS?

**Comment by thelwyn** [comment] 2021-02-09 23:36
> 
> 
> Are you using Umbrel OS?

Yes, from getumbrel.com , on a RPi4.

**Comment by nmfretz** [comment] 2023-05-27 00:24
closing old support issue

**Closed by nmfretz** 2023-05-27 00:24 UTC
