### ISSUE TITLE
For new users, starting a lightning channel is difficult and ineffective

### ISSUE THREAD

**Issue by MickMorucci** [getumbrel/umbrel#811] opened 2021-06-04 10:30 UTC
**User Problem:**
- As a new lightning channel user, I don't know **which** channels I should connect to,
- As a new lightning channel user, I don't know which channels are better & most profitable/effective to connect to.
- As a new lightning channel user, I fail to connect to the majority of lightning addresses.
  
**Suggestions:**
- How may we use software to help new lightning users set-up optimal channels. These may be channels that have most active and recurring transactions.
   - Story: User trying to open a lightning channel is provided a list of options of channels to connect to.

**Comment by notleanbarba** [comment] 2021-06-15 16:24
I guess it could suggest a random peer from top 25 BOS ranking.

**Comment by Darth-Coin** [comment] 2021-07-04 10:08
Your lack of knowledge about how to use LN is not a bug/issue of Umbrel.
You just need to learn and read more about how to use LN
[Getting Started with Umbrel](https://community.getumbrel.com/t/getting-started-with-umbrel-node/51)
[Tutorials about LN](https://community.getumbrel.com/t/list-of-video-tutorials-to-start-learning-nodes-related/272)
[Opening channels](https://community.getumbrel.com/t/opening-channels-requests/66)
[Excellent video guide exactly about your case](https://www.youtube.com/watch?v=KItleddMYFU) by BTC Sessions (btw, his YT channel is full of tutorials with LN)
[Akex Bossworth about channels management](https://youtu.be/HlPIB6jt6ww) - very good presentation, also his [Twitter feed](https://twitter.com/alexbosworth) is like a LN manual

So start learning

**Comment by notleanbarba** [comment] 2021-07-04 10:43
Umbrel is clearly pointed to end users with none or little technical knowledge. 

This is not a bug but it's desirable that everyone can easily understand what's going on without to much research. 

Also I think the web app could have hints to guide the user in what to do.

**Comment by notleanbarba** [comment] 2021-07-04 10:44
Umbrel is clearly pointed to end users with none or little technical knowledge.

This is not a bug but it's desirable that everyone can easily understand what's going on without to much research.

Also I think the web app could have hints to guide the user in what to do.

> Your lack of knowledge about how to use LN is not a bug/issue of Umbrel.
> You just need to learn and read more about how to use LN
> [Getting Started with Umbrel](https://community.getumbrel.com/t/getting-started-with-umbrel-node/51)
> [Tutorials about LN](https://community.getumbrel.com/t/list-of-video-tutorials-to-start-learning-nodes-related/272)
> [Opening channels](https://community.getumbrel.com/t/opening-channels-requests/66)
> [Excellent video guide exactly about your case](https://www.youtube.com/watch?v=KItleddMYFU) by BTC Sessions (btw, his YT channel is full of tutorials with LN)
> [Akex Bossworth about channels management](https://youtu.be/HlPIB6jt6ww) - very good presentation, also his [Twitter feed](https://twitter.com/alexbosworth) is like a LN manual
> 
> So start learning

**Comment by Darth-Coin** [comment] 2021-07-04 11:47
Yes the Umbrel dashboard already have that link already at the bottom of the page, you just have to click it and you will enter into Umbrel community forum with loads of info.
![image](https://user-images.githubusercontent.com/56997124/124383721-4beb0800-dcce-11eb-93f6-be9d89fc3608.png)

**Comment by notleanbarba** [comment] 2021-07-04 12:01
It's an app, man. Do you have lessons or a community forum to use twitter?

**Comment by MickMorucci** [comment] 2021-07-05 11:43
Appreciate all the feedback. I'm learning a lot more about Lightning as we speak, and thanks for the resources provided by Darth-Coin. 

But I'm going to push back on that comment. As Notleanbarba pointed out, Umbrel is directed at users with low technical skills and the channel opening is by far the biggest issue in the set up process. I don't expect to be 'educated' but to be guided and supported. 

On education and guidance:
- Umbrel could provide links to content on how to set up a channel.

Support channel opening:
- Umbrel could suggest a random peer from top 25 BOS ranking (good idea @notleanbarba ) - through a drop down - to prevent user having to go back and fourth with the explorer
- Umbrel could also suggest growing Lightning channels with high demand / high fees, where there is potential for arbitrage. This could help users earn higher fees and create a more competitive pricing overall.

**Comment by D4nte** [comment] 2021-07-06 11:26
May I suggest to look into Muun Wallet is doing? Excellent UX of merged balance and no exposure of channels management to the user.
Ultimately, I would expect users to not have to know what a channel is. The same way that someone does not need to know what a spark plug is to drive a car.

**Comment by Darth-Coin** [comment] 2021-07-06 11:31
> May I suggest to look into what Muun Wallet is doing? Excellent UX of merged balance and no exposure of channels management to the user.
> Ultimately, I would expect users to not have to know what a channel is. The same way that someone does not need to know what a spark plug is to drive a car.

This is offtopic. We are talking about running nodes, not wallets without nodes.
Running a node is an important thing and separate from just using a wallet.

**Comment by D4nte** [comment] 2021-07-07 00:06
https://github.com/getumbrel/umbrel-dashboard/issues/285 should help with this issue.

> Running a node is an important thing and separate from just using a wallet.

If it is an "important thing" then what is wrong with lowering the barrier of entry by reducing the knowledge needed to run a node. Isn't it exactly what umbrel is for by the way?

**Comment by notleanbarba** [comment] 2021-07-07 00:25
Yeah, we are running nodes not building them.

> > May I suggest to look into what Muun Wallet is doing? Excellent UX of merged balance and no exposure of channels management to the user.
> > Ultimately, I would expect users to not have to know what a channel is. The same way that someone does not need to know what a spark plug is to drive a car.
> 
> This is offtopic. We are talking about running nodes, not wallets without nodes.
> Running a node is an important thing and separate from just using a wallet.

**Comment by MickMorucci** [comment] 2021-07-07 07:58
Channel opening is a critical part of the process, but users should be supported through it as much as possible, to enable users to:
- earn higher fees
- have a more secure connection to lightning network.

**Comment by atap101** [comment] 2021-08-02 05:34
can anyone direct me in how to pay for liquidity so i can open more channels on my node 1m seams to do it but isk how to send the payment with hodl is there any other way ?? i got the best hardware for the node and capacity 2x recommended for ram and mem

**Closed** 2023-05-29 04:58 UTC
