### ISSUE TITLE
Adding new app proposal - BoS

### ISSUE THREAD

**Issue by Darth-Coin** [getumbrel/umbrel#697] opened 2021-04-05 10:58 UTC
I suggest to add as an app in Umbrel the Balance of Satoshi
https://github.com/alexbosworth/balanceofsatoshis
Or something related, to help users having a nice and easy tool to rebalance their channels.
I was trying to make rebalancing channels through RTL and Thunderhub, but with no success.
We need something, a tool or service that is running in background, or manually activated by the user, that is doing a rebalancing anytime is needed.
Please take in consideration this.

**Comment by lukechilds** [comment] 2021-04-05 14:32
Closing as duplicate of https://github.com/getumbrel/umbrel/issues/652.

>I was trying to make rebalancing channels through RTL and Thunderhub, but with no success.

Have you tried Lightning Terminal?

**Closed by lukechilds** 2021-04-05 14:32 UTC
