### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by AaronDewes** [getumbrel/umbrel#291] opened 2020-10-17 16:55 UTC
> For the avoidance of doubt, You do not have permission under this Public License to Share Adapted Material.

If I understand this part correctly, the NoDerivatives version
disallows contributing to Umbrel, because by submitting a PR, I share a modified version of Umbrel publicly.

**Comment by mayankchhabra** [comment] 2020-10-18 11:26
Unfortunately that's one downside of using a readymade license. It's on our list to do a custom license that does allow derivate work for upstream contributions. For now, we're happy to provide explicit written consent to every developer making contributions (on request).

**Comment by mayankchhabra** [comment] 2020-10-18 17:03
Closing this for now as it's a long-term to-do. Meanwhile @AaronDewes if you'd like an explicit written consent, feel free to hit me up directly.

**Closed by mayankchhabra** 2020-10-18 17:03 UTC

**Comment by AaronDewes** [comment] 2020-10-19 09:51
I wrote a license you could use, it is adapted from the Licnese you're using currently, available under CC0 and provided without warranty or liability. It hasn't been checked by a lawyer, and there might be legal loopholes. 



## Aaron Dewes Public License v0.1

By exercising the Licensed Rights (defined below), You accept and agree to be bound by the terms and conditions of this Aaron Dewes License v0.1 ("Public License"). To the extent this Public License may be interpreted as a contract, You are granted the Licensed Rights in consideration of Your acceptance of these terms and conditions, and the Licensor grants You such rights in consideration of benefits the Licensor receives from making the Licensed Material available under these terms and conditions.

### Section 1 – Definitions.

a. __Adapted Material__ means material subject to Copyright and Similar Rights that is derived from or based upon the Licensed Material and in which the Licensed Material is translated, altered, arranged, transformed, or otherwise modified in a manner requiring permission under the Copyright and Similar Rights held by the Licensor. For purposes of this Public License, where the Licensed Material is a musical work, performance, or sound recording, Adapted Material is always produced where the Licensed Material is synched in timed relation with a moving image.

b. __Copyright and Similar Rights__ means copyright and/or similar rights closely related to copyright including, without limitation, performance, broadcast, sound recording, and Sui Generis Database Rights, without regard to how the rights are labeled or categorized. For purposes of this Public License, the rights specified in Section 2(b)(1)-(2) are not Copyright and Similar Rights.

e. __Effective Technological Measures__ means those measures that, in the absence of proper authority, may not be circumvented under laws fulfilling obligations under Article 11 of the WIPO Copyright Treaty adopted on December 20, 1996, and/or similar international agreements.

f. __Exceptions and Limitations__ means fair use, fair dealing, and/or any other exception or limitation to Copyright and Similar Rights that applies to Your use of the Licensed Material.

g. __License Elements__ means the license attributes listed in the name of a Creative Commons Public License. The License Elements of this Public License are Attribution, NonCommercial, and ShareAlike.

h. __Licensed Material__ means the artistic or literary work, database, or other material to which the Licensor applied this Public License.

i. __Licensed Rights__ means the rights granted to You subject to the terms and conditions of this Public License, which are limited to all Copyright and Similar Rights that apply to Your use of the Licensed Material and that the Licensor has authority to license.

h. __Licensor__ means the individual(s) or entity(ies) granting rights under this Public License.

i. __NonCommercial__ means not primarily intended for or directed towards commercial advantage or monetary compensation. For purposes of this Public License, the exchange of the Licensed Material for other material subject to Copyright and Similar Rights by digital file-sharing or similar means is NonCommercial provided there is no payment of monetary compensation in connection with the exchange.

j. __Share__ means to provide material to the public by any means or process that requires permission under the Licensed Rights, such as reproduction, public display, public performance, distribution, dissemination, communication, or importation, and to make material available to the public including in ways that members of the public may access the material from a place and at a time individually chosen by them.

k. __Sui Generis Database Rights__ means rights other than copyright resulting from Directive 96/9/EC of the European Parliament and of the Council of 11 March 1996 on the legal protection of databases, as amended and/or succeeded, as well as other essentially equivalent rights anywhere in the world.

l. __You__ means the individual or entity exercising the Licensed Rights under this Public License. Your has a corresponding meaning.

### Section 2 – Scope.

a. ___License grant.___

   1. Subject to the terms and conditions of this Public License, the Licensor hereby grants You a worldwide, royalty-free, non-sublicensable, non-exclusive, irrevocable license to exercise the Licensed Rights in the Licensed Material to:

        A. reproduce and Share the Licensed Material, in whole or in part, for NonCommercial purposes only; and

        B. produce, reproduce, and Share Adapted Material if you comply with the conditions defined in section 8 of this license.

   2. __Exceptions and Limitations.__ For the avoidance of doubt, where Exceptions and Limitations apply to Your use, this Public License does not apply, and You do not need to comply with its terms and conditions.

   3. __Term.__ The term of this Public License is specified in Section 6(a).

   4. __Media and formats; technical modifications allowed.__ The Licensor authorizes You to exercise the Licensed Rights in all media and formats whether now known or hereafter created, and to make technical modifications necessary to do so. The Licensor waives and/or agrees not to assert any right or authority to forbid You from making technical modifications necessary to exercise the Licensed Rights, including technical modifications necessary to circumvent Effective Technological Measures. For purposes of this Public License, simply making modifications authorized by this Section 2(a)(4) never produces Adapted Material.

   5. __Downstream recipients.__

        A. __Offer from the Licensor – Licensed Material.__ Every recipient of the Licensed Material automatically receives an offer from the Licensor to exercise the Licensed Rights under the terms and conditions of this Public License.

        B. __No downstream restrictions.__ You may not offer or impose any additional or different terms or conditions on, or apply any Effective Technological Measures to, the Licensed Material if doing so restricts exercise of the Licensed Rights by any recipient of the Licensed Material.

   6. __No endorsement.__ Nothing in this Public License constitutes or may be construed as permission to assert or imply that You are, or that Your use of the Licensed Material is, connected with, or sponsored, endorsed, or granted official status by, the Licensor or others designated to receive attribution as provided in Section 3(a)(1)(A)(i).

b. ___Other rights.___

   1. Moral rights, such as the right of integrity, are not licensed under this Public License, nor are publicity, privacy, and/or other similar personality rights; however, to the extent possible, the Licensor waives and/or agrees not to assert any such rights held by the Licensor to the limited extent necessary to allow You to exercise the Licensed Rights, but not otherwise.

   2. Patent and trademark rights are not licensed under this Public License.

   3. To the extent possible, the Licensor waives any right to collect royalties from You for the exercise of the Licensed Rights, whether directly or through a collecting society under any voluntary or waivable statutory or compulsory licensing scheme. In all other cases the Licensor expressly reserves any right to collect such royalties, including when the Licensed Material is used other than for NonCommercial purposes.

### Section 3 – License Conditions.

Your exercise of the Licensed Rights is expressly made subject to the following conditions.

a. ___Attribution.___

   1. If You Share the Licensed Material (including in modified form), You must:

       A. retain the following if it is supplied by the Licensor with the Licensed Material:

         i. identification of the creator(s) of the Licensed Material and any others designated to receive attribution, in any reasonable manner requested by the Licensor (including by pseudonym if designated);

         ii. a copyright notice;

         iii. a notice that refers to this Public License;

         iv. a notice that refers to the disclaimer of warranties;

         v. a URI or hyperlink to the Licensed Material to the extent reasonably practicable;

       B. indicate if You modified the Licensed Material and retain an indication of any previous modifications; and

       C. indicate the Licensed Material is licensed under this Public License, and include the text of, or the URI or hyperlink to, this Public License.

   2. You may satisfy the conditions in Section 3(a)(1) in any reasonable manner based on the medium, means, and context in which You Share the Licensed Material. For example, it may be reasonable to satisfy the conditions by providing a URI or hyperlink to a resource that includes the required information.

   3. If requested by the Licensor, You must remove any of the information required by Section 3(a)(1)(A) to the extent reasonably practicable.

### Section 4 – Sui Generis Database Rights.

Where the Licensed Rights include Sui Generis Database Rights that apply to Your use of the Licensed Material:

a. for the avoidance of doubt, Section 2(a)(1) grants You the right to extract, reuse, reproduce, and Share all or a substantial portion of the contents of the database for NonCommercial purposes only;

b. if You include all or a substantial portion of the database contents in a database in which You have Sui Generis Database Rights, then the database in which You have Sui Generis Database Rights (but not its individual contents) is Adapted Material, including for purposes of Section 3(b); and

c. You must comply with the conditions in Section 3(a) if You Share all or a substantial portion of the contents of the database.

For the avoidance of doubt, this Section 4 supplements and does not replace Your obligations under this Public License where the Licensed Rights include other Copyright and Similar Rights.

### Section 5 – Disclaimer of Warranties and Limitation of Liability.

a. __Unless otherwise separately undertaken by the Licensor, to the extent possible, the Licensor offers the Licensed Material as-is and as-available, and makes no representations or warranties of any kind concerning the Licensed Material, whether express, implied, statutory, or other. This includes, without limitation, warranties of title, merchantability, fitness for a particular purpose, non-infringement, absence of latent or other defects, accuracy, or the presence or absence of errors, whether or not known or discoverable. Where disclaimers of warranties are not allowed in full or in part, this disclaimer may not apply to You.__

b. __To the extent possible, in no event will the Licensor be liable to You on any legal theory (including, without limitation, negligence) or otherwise for any direct, special, indirect, incidental, consequential, punitive, exemplary, or other losses, costs, expenses, or damages arising out of this Public License or use of the Licensed Material, even if the Licensor has been advised of the possibility of such losses, costs, expenses, or damages. Where a limitation of liability is not allowed in full or in part, this limitation may not apply to You.__

c. The disclaimer of warranties and limitation of liability provided above shall be interpreted in a manner that, to the extent possible, most closely approximates an absolute disclaimer and waiver of all liability.

### Section 6 – Term and Termination.

a. This Public License applies for the term of the Copyright and Similar Rights licensed here. However, if You fail to comply with this Public License, then Your rights under this Public License terminate automatically.

b. Where Your right to use the Licensed Material has terminated under Section 6(a), it reinstates:

   1. automatically as of the date the violation is cured, provided it is cured within 30 days of Your discovery of the violation; or

   2. upon express reinstatement by the Licensor.

   For the avoidance of doubt, this Section 6(b) does not affect any right the Licensor may have to seek remedies for Your violations of this Public License.

c. For the avoidance of doubt, the Licensor may also offer the Licensed Material under separate terms or conditions or stop distributing the Licensed Material at any time; however, doing so will not terminate this Public License.

d. Sections 1, 5, 6, 7, and 9 survive termination of this Public License.

### Section 7 – Other Terms and Conditions.

a. The Licensor shall not be bound by any additional or different terms or conditions communicated by You unless expressly agreed.

b. Any arrangements, understandings, or agreements regarding the Licensed Material not stated herein are separate from and independent of the terms and conditions of this Public License.

### Section 8 - Sharing modifications

In addition to the conditions in Section 3(a), if You Share Adapted Material You produce, the following conditions also apply.

1. The Adapter’s License You apply must be this license.

2. You must not share your modified version except by opening a pull request on the official Umbrel GitHub repos.

3. If your pull request is closed, you must delete the git branch or the GitHub repo that contains your changes within 10 days. This does not apply if the pull request is merged into an official Umbrel repo.

4. The Umbrel team may disallow you from contributing by either commenting on one of your PRs before closing, if this happens, you are not allowed to open a PR again, thus you must not share any modified version of

### Section 9 – Interpretation.

a. For the avoidance of doubt, this Public License does not, and shall not be interpreted to, reduce, limit, restrict, or impose conditions on any use of the Licensed Material that could lawfully be made without permission under this Public License.

b. To the extent possible, if any provision of this Public License is deemed unenforceable, it shall be automatically reformed to the minimum extent necessary to make it enforceable. If the provision cannot be reformed, it shall be severed from this Public License without affecting the enforceability of the remaining terms and conditions.

c. No term or condition of this Public License will be waived and no failure to comply consented to unless expressly agreed to by the Licensor.

d. Nothing in this Public License constitutes or may be interpreted as a limitation upon, or waiver of, any privileges and immunities that apply to the Licensor or You, including from the legal processes of any jurisdiction or authority.

**Comment by mayankchhabra** [comment] 2020-11-05 10:27
@AaronDewes, is there something that you can't do? Lol, you're a rockstar, dude. Thanks for taking the time to modify the license. Overall, the modifications look pretty good.

We think a custom license can do more harm than good if it's not written by a professional legal team, since there are things that we might overlook/skip. For that reason, we decided to stick to CC-BY-NC-ND as it's well tested and understood.

**Comment by ignoramous** [comment] 2020-12-17 11:39
@mayankchhabra check out https://polyformproject.org/licenses/ and https://commonsclause.com/

**Comment by mayankchhabra** [comment] 2020-12-17 14:42
Interesting. Thanks, @ignoramous! We'll go over these.

**Comment by mayankchhabra** [comment] 2020-12-17 14:43
Interesting. Thanks, @ignoramous! We'll go through these.

**Comment by skacfjin** [comment] 2021-03-12 12:36
What is the reason to not use GPL/MIT/whatever other licence?

**Comment by AaronDewes** [comment] 2021-03-12 12:38
https://twitter.com/AaronDewes/status/1370022491356164096

**Comment by junderw** [comment] 2021-03-12 13:19
FYI if the concern is Trademark use, Apache License 2.0 is usually used for that purpose.

**Comment by junderw** [comment] 2021-03-12 13:20
Also, just a reminder that you need permission from all 15 contributors to change the license, otherwise you need to remove any code left over from that person (using git blame etc.)

**Comment by junderw** [comment] 2021-03-12 13:22
This comment serves as "idgaf" and whatever license you guys choose is fine, I'm cool with any license on https://choosealicense.com/licenses/

**Comment by raucao** [comment] 2021-03-12 18:11
> FYI if the concern is Trademark use, Apache License 2.0 is usually used for that purpose.

Another, similar option would be MPL.

**Comment by mayankchhabra** [comment] 2021-03-16 06:18
Thanks for the feedback, guys! I understand CC licenses aren't the best choice for software.

Some thoughts on why we chose this license. Umbrel isn't a hobby project and we don't want to be at the mercy of donations to work on it. (We all know how that can end up — when the donations dry out, maintainers abandon the project, leaving the users stuck in a limbo forever.)

Our goal is to build a self-sustaining company that offers products/services which users are happy to pay for. A license like CC-BY-NC-ND on parts of codebase buys us time and flexibility to experiment with multiple business models in the long-term which would otherwise not be feasible on more permissive licenses. It strikes a good balance of providing complete freedom for personal use, while restricting commercial use and distribution. I think it's for the same reasons that other Bitcoin node offerings use this or a similar non-commercial license.

That being said, once we've figured out a sustainable business model, we'll transition to a more suitable license (but this is not a short-term priority).

**Comment by raucao** [comment] 2021-03-16 11:47
How is this addressing any of the actual feedback and problems with the license? There is no "complete freedom for personal use", if even just pushing a commit to my forked GitHub repo is violating the license. Neither can you legally share an intentional fork for rule changes with other personal users, which is one of the major pillars of bitcoin node/user freedom, and the bitcoin consensus model.

Unfortunately, it seems to me like the developers here have no experience in opensource licensing, or frankly the benefits of opensource software in general. And yet, instead of listening to potential contributors telling them outright that they cannot contribute to, and/or use the software as it is now, the final comment closing the issue is mostly hand waving about people trying to fix the license issue not being serious about business usage ("Umbrel isn't a hobby project").

Someone on Twitter even proposed that hardware vendors paying for license fees is seriously being considered as a business model, which, in my opinion, is a downright absurd thing to say in 2021 about a project claiming to uphold opensource values. This product literally has wallets for almost-zero-fee payments as its main utility. How is it not obvious that users donating to the Umbrel organization directly from within the product, even as a default setting, would be the modern, *Bitcoin* way to go, and that license fees from hardware vendors is the most 1990s-Microsoft, anti-open-source model you could even come up with?

If this sounds harsh, I apologize. But instead of solving the license issue, you have basically only demonstrated that you have not understood the license issue. Which is just sad news for some of us potential users and contributors. However, it's obviously entirely the choice of the existing copyright holders.

For me personally, after initially having been excited about the good UX, it just means recommending against using the product, when someone asks me about it. And as both a full-time opensource developer and bitcoin node operator, I would ask that you at least remove the Satoshi quote about opensource from the bottom of your README, so that people not opening the license file aren't misled until they do. :pray: 

Finally, just in case you hadn't seen it before, here's the Creative Commons authors themselves recommending against using their license for software. Make of that what you will: https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

**Comment by wiz** [comment] 2021-03-16 14:12
> you need permission from all 15 contributors to change the license

It seems that Umbrel might not be legally licensed at all right now, since AFAICT the contributors to the MIT licensed Umbrel open source project didn't consent to changing from MIT license to a non-free license in https://github.com/getumbrel/umbrel/pull/235 and I doubt they would want the project to not be FOSS anymore. It looks like the Umbrel guys have quite a legal mess to fix.

> if you'd like an explicit written consent, feel free to hit me up directly.

Unless you have some other agreements in place, you can't give consent on behalf of all of the original authors / copyright holders to the Umbrel open source project...

**Comment by AaronDewes** [comment] 2021-03-16 14:40
> Someone on Twitter even proposed that hardware vendors paying for license fees is seriously being considered as a business model, which, in my opinion, is a downright absurd thing to say in 2021 about a project claiming to uphold opensource values. This product literally has wallets for almost-zero-fee payments as its main utility. How is it not obvious that users donating to the Umbrel organization directly from within the product, even as a default setting, would be the modern, Bitcoin way to go, and that license fees from hardware vendors is the most 1990s-Microsoft, anti-open-source model you could even come up with?

This is actually an idea we had, and I was the one who said it.

This is not official, and what I'm saying doesn't man a license change, but we're discussing about the license of Umbrel.

**Comment by nolim1t** [comment] 2021-03-16 15:35
> > you need permission from all 15 contributors to change the license
> 
> 
> 
> It seems that Umbrel might not be legally licensed at all right now, since AFAICT the contributors to the MIT licensed Umbrel open source project didn't consent to changing from MIT license to a non-free license in https://github.com/getumbrel/umbrel/pull/235 and I doubt they would want the project to not be FOSS anymore. It looks like the Umbrel guys have quite a legal mess to fix.
> 
> 
> 
> > if you'd like an explicit written consent, feel free to hit me up directly.
> 
> 
> 
> Unless you have some other agreements in place, you can't give consent on behalf of all of the original authors / copyright holders to the Umbrel open source project...

I sure did not consent to that..   it wasn't merged by me or even given a chance to review it.

I had full commit access at that time

**Comment by ignoramous** [comment] 2021-03-16 16:03
MIT does allow changing the license to a more restrictive one without requiring consent from existing developers. The problem here is that the CreativeCommons license isn't really meant for code.

@mayankchhabra, as everyone else has mentioned, you're in a for a legal mess by punting the licensing to later.

I am not an expert, but I see a few ways to resolve the current quagmire:

(in the increasing order of copyleft)
1. [MIT + Commons Clause](https://commonsclause.com/).
2. [MIT + BSL](https://mariadb.com/bsl11/).
3. The xGPLv3s: AGPLv3 or GPLv3.
4. [SSPL](https://www.mongodb.com/licensing/server-side-public-license).

...of which only the xGPLs are F/OSS.

To avoid the issue with future license changes, consider [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement)ing external contributions, so the company behind Umbrel retains the copyright. Copyright transfers are illegal in certain jurisdictions like Germany, so I am not sure how you should treat contributions from German nationals (and others in similar jurisdictions).

---

Read also:

http://dtrace.org/blogs/bmc/2018/12/14/open-source-confronts-its-midlife-crisis/

https://www.joelonsoftware.com/2002/06/12/strategy-letter-v/

http://dtrace.org/blogs/bmc/2004/12/16/the-economics-of-software-redux/

**Comment by nolim1t** [comment] 2021-03-16 16:06
CLAing developers also opens a can of worms.. not many ppl want to dox themselves

**Comment by AaronDewes** [comment] 2021-03-16 17:34
> Copyright transfers are illegal in certain jurisdictions like Germany, so I am not sure how you should treat contributions from German nationals (and from others who are in similar jurisdictions).

As someone who lives in Germany, I actually have researched a bit about this. Basically, Germany has the "Urheberrecht" which is automatically granted to everyone who creates something. "Nutzungsrecht", on the other hand, can be given to someone and basically remove every permission the auther has under the "Urheberrecht", so the "Nutzungsrecht" is more like the american Copyright.

**Comment by josibake** [comment] 2021-06-15 14:31
> Umbrel isn't a hobby project and we don't want to be at the mercy of donations to work on it. (We all know how that can end up — when the donations dry out, maintainers abandon the project, leaving the users stuck in a limbo forever.)
> 
> Our goal is to build a self-sustaining company that offers products/services which users are happy to pay for. A license like CC-BY-NC-ND on parts of codebase buys us time and flexibility to experiment with multiple business models in the long-term which would otherwise not be feasible on more permissive licenses.

related to your license, why are you "welcoming" and accepting free contributions from the open source community to bootstrap a for profit company? of the business models you are exploring, are you planning to fairly compensate the people who have contributed?

**Comment by TheBitFish** [comment] 2021-06-30 02:06
@mayankchhabra This really needs to be addressed. I was personally using and recommending Umbrel, and looking to contribute (and know of several other devs that were interested) but am now 100% avoiding this project. The creative commons license is not an open source software license. Also the replacement of the MIT license does not appear to have been agreed to by all contributors thus the project is currently in violation of its own license.

This is a mess.

Not to mention the ridiculous stance of "welcoming contributions" with "plans to monetize the project". Are you planning to profit share? My guess is no.

The Umbrel team should really be more responsible than this considering the rapid adoption of this project in the Lightning Network community. This is rent seeking behavior, the antithesis of Bitcoin.

**Comment by AaronDewes** [comment] 2021-06-30 04:47
> Also the replacement of the MIT license does not appear to have been agreed to by all contributors thus the project is currently in violation of its own license.

While I'm no longer working with Umbrel, I still want to point out that the MIT license allows changing the license to anything as long as you keep copyright notes.
