### ISSUE TITLE
Start/stop is unreliable

### ISSUE THREAD

**Issue by kroese** [getumbrel/umbrel#1458] opened 2022-06-25 03:09 UTC
Ever since upgrading to 0.5 the starting and stopping became very unreliable. 

After rebooting there is almost always one or two random apps missing (no docker containers created for them), and I have to keep rebooting until Im so lucky that all of them were launched.

Same goes for stopping. Almost every time there is one or more containers failing to stop correctly, and I have to repeat the stop script until it works. The error I am getting while stopping is:

```
The Compose file is invalid because:
Service app_proxy has neither an image nor a build context specified. At least one must be provided.
```

After which I get an error about `umbrel_main_network` not being removed because there are still endpoints attached (because of the containers that did not stop).

When starting it is the same error:

```
startup[5462]: The Compose file is invalid because:
startup[5462]: Service app_proxy has neither an image nor a build context specified. At least one must be provided.
```

But also this one:

```
startup[4811]: /home/umbrel/umbrel/scripts/../scripts/app: line 97: echo: write error: Broken pipe
startup[5384]: /home/umbrel/umbrel/scripts/../scripts/app: line 201: echo: write error: Broken pipe
```

I already run into similar problems during the upgrade (see #1413 ) but now I keep running into it during daily use. 

Can this please be looked into, because it has started to become really annoying.

**Comment by lukechilds** [comment] 2022-06-25 14:11
Thanks for this detailed report @kroese, I have also noticed this behaviour. Can I ask, how many apps do you have installed?

@nevets963 this sounds related to the stuff we were discussing the other day, where we were alluding to some kind of fs thrashing issue. Although the logs @kroese has provided indicate maybe it's more closely Docker related than fs?

**Comment by nevets963** [comment] 2022-07-12 08:40
Folks, a quick update; I've root caused this issue to be the `--quiet` flag here: https://github.com/getumbrel/umbrel/blob/0f2212821bd1fc2a617b389fd26fcde97c5103d3/scripts/app#L201

Tbh, I don't know 100% why this sometimes fails, but a fix for this issue is included in Umbrel v0.5.1

**Comment by lukechilds** [comment] 2022-07-14 12:18
This is now resolved in Umbrel 0.5.1, thanks for the detailed report @kroese!

**Closed by lukechilds** 2022-07-14 12:18 UTC

**Comment by martinbarilik** [comment] 2023-01-09 20:57
Hi, i am fighting this bug on umbrel 0.5.3

currently installed apps: bitcoin, mempool, btc rpc explorer, pi-hole, specter-desktop, and electrs

none of the above docker-compose is working

```
umbrel@umbrel:~/umbrel/app-data/mempool $ docker-compose logs mempool
ERROR: The Compose file is invalid because:
Service app_proxy has neither an image nor a build context specified. At least one must be provided.
```

only difference is bitcoin 

```
umbrel@umbrel:~/umbrel/app-data/bitcoin $ docker-compose logs bitcoin
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.bitcoind.ports contains an invalid type, it should be a number, or an object
services.bitcoind.ports contains an invalid type, it should be a number, or an object
services.bitcoind.ports value [':', ':'] has non-unique elements
```

i run, but without any change in response

```
umbrel@umbrel:~/umbrel/app-data/mempool $ sudo ~/umbrel/scripts/stop
Killing background services
Stopping installed apps...

Stopping app mempool...
Stopping app specter-desktop...
Stopping app btc-rpc-explorer...
Stopping app electrs...
Stopping app pi-hole...
Stopping app bitcoin...
Stopping btc-rpc-explorer_web_1        ... 
Stopping btc-rpc-explorer_app_proxy_1  ... 
Stopping btc-rpc-explorer_tor_server_1 ... 
Stopping specter-desktop_tor_server_1 ... 
Stopping specter-desktop_web_1        ... 
Stopping specter-desktop_app_proxy_1  ... 
Stopping bitcoin_server_1      ... 
Stopping bitcoin_i2pd_daemon_1 ... 
Stopping bitcoin_tor_server_1  ... 
Stopping bitcoin_bitcoind_1    ... 
Stopping bitcoin_tor_1         ... 
Stopping bitcoin_app_proxy_1   ... 
Stopping mempool_tor_server_1 ... 
Stopping mempool_api_1        ... 
Stopping mempool_web_1        ... 
Stopping mempool_app_proxy_1  ... 
Stopping mempool_mariadb_1    ... 
Stopping electrs_electrs_1    ... 
Stopping electrs_app_1        ... 
Stopping bitcoin_server_1      ... done
Stopping electrs_tor_server_1 ... 
Stopping electrs_app_1        ... done
Stopping btc-rpc-explorer_web_1        ... done
Stopping pi-hole_server_1     ... done
Stopping mempool_tor_server_1 ... done
Stopping bitcoin_tor_server_1  ... done
Stopping pi-hole_tor_server_1 ... done
Stopping electrs_tor_server_1 ... done
Removing btc-rpc-explorer_tor_server_1 ... done
Going to remove pi-hole_tor_server_1, pi-hole_server_1, pi-hole_app_proxy_1
Removing pi-hole_tor_server_1 ... done
Removing pi-hole_server_1     ... done
Stopping mempool_mariadb_1    ... done
Going to remove mempool_tor_server_1, mempool_api_1, mempool_web_1, mempool_app_proxy_1, mempool_mariadb_1
Removing mempool_tor_server_1 ... done
Removing mempool_api_1        ... done
Stopping bitcoin_bitcoind_1    ... done
Stopping specter-desktop_web_1        ... done
Removing mempool_mariadb_1    ... done
Going to remove bitcoin_server_1, bitcoin_i2pd_daemon_1, bitcoin_tor_server_1, bitcoin_bitcoind_1, bitcoin_tor_1, bitcoin_app_proxy_1
Going to remove specter-desktop_tor_server_1, specter-desktop_web_1, specter-desktop_app_proxy_1
Removing bitcoin_server_1      ... 
Removing bitcoin_i2pd_daemon_1 ... 
Removing bitcoin_tor_server_1  ... 
Removing bitcoin_server_1      ... done
Stopping electrs_electrs_1    ... done
Removing bitcoin_tor_server_1  ... done
Removing bitcoin_bitcoind_1    ... done
Removing bitcoin_tor_1         ... done
Removing specter-desktop_app_proxy_1  ... done
Going to remove electrs_electrs_1, electrs_app_1, electrs_tor_1, electrs_tor_server_1, electrs_app_proxy_1
Removing electrs_electrs_1    ... done
Removing electrs_app_1        ... done
Removing electrs_tor_1        ... done
Removing electrs_tor_server_1 ... done
Removing electrs_app_proxy_1  ... done

Stopping Docker services...

Stopping nginx      ... done
Stopping tor_proxy  ... done
Stopping auth       ... done
Stopping tor_server ... done
Stopping dashboard  ... done
Stopping manager    ... done
Removing nginx      ... done
Removing tor_proxy  ... done
Removing auth       ... done
Removing tor_server ... done
Removing dashboard  ... done
Removing manager    ... done
Removing network umbrel_main_network
```

```
umbrel@umbrel:~/umbrel/app-data/mempool $ sudo ~/umbrel/scripts/start

======================================
============= STARTING ===============
============== UMBREL ================
======================================

Setting environment variables...

Starting karen...

Starting status monitors...
Starting memory monitor...

Starting backup monitor...

Starting decoy backup trigger...


Starting Docker services...

Creating network "umbrel_main_network" with the default driver
Creating dashboard  ... done
Creating manager    ... done
Creating auth       ... done
Creating tor_proxy  ... done
Creating tor_server ... done
Creating nginx      ... done

Removing status server iptables entry...
No existing iptables entry found.

Starting installed apps...

Starting app btc-rpc-explorer...
Starting app mempool...
Starting app pi-hole...
Starting app bitcoin...
Starting app specter-desktop...
Starting app electrs...
Executing hook: /home/umbrel/umbrel/app-data/bitcoin/hooks/pre-start
Executing hook: /home/umbrel/umbrel/app-data/electrs/hooks/pre-start
Creating mempool_app_proxy_1 ... 
Creating mempool_tor_server_1 ... 
Creating mempool_web_1        ... 
Creating btc-rpc-explorer_app_proxy_1 ... 
Creating mempool_mariadb_1    ... 
Creating btc-rpc-explorer_tor_server_1 ... 
Creating btc-rpc-explorer_web_1        ... 
Creating mempool_api_1        ... 
Creating specter-desktop_web_1 ... 
Creating specter-desktop_tor_server_1 ... 
Creating specter-desktop_app_proxy_1  ... 
Creating pi-hole_app_proxy_1 ... 
Creating pi-hole_tor_server_1 ... 
Creating pi-hole_server_1     ... 
Creating electrs_tor_server_1 ... 
Creating electrs_app_proxy_1  ... 
Creating electrs_tor_1        ... 
Creating electrs_electrs_1    ... 
Creating mempool_app_proxy_1  ... done
Creating bitcoin_bitcoind_1    ... done
Creating electrs_app_proxy_1  ... done
Creating bitcoin_app_proxy_1   ... done
Creating bitcoin_tor_1         ... done
Creating pi-hole_server_1     ... done
Creating bitcoin_server_1      ... done

Umbrel is now accessible at
  http://umbrel.local
  http://192.168.1.100
  http://4soxgvfi2mhwi5xu7xcbievfuezgz37v6drflqql5itt5euonjq4zpqd.onion
```

**Comment by nevets963** [comment] 2023-01-09 23:29
@martinbarilik What you're experiencing is by design as it is not possible to interact with the apps directly using `docker-compose`. This is because an app's `docker-compose.yml` file will use variables that our command line tools export.

If you want to directly interact with an app, you can run the following: 
```
sudo ~/umbrel/scripts/app compose <app_id> <docker_compose_subcommand>
```

E.g: 
```
sudo ~/umbrel/scripts/app compose mempool logs
```

**Comment by martinbarilik** [comment] 2023-01-10 07:50
Yeah, i realized that after digging into scripts. Thanks tho ...
