### ISSUE TITLE
Switch between mainnet, testnet and regtest

### ISSUE THREAD

**Issue by mayankchhabra** [getumbrel/umbrel#329] opened 2020-12-04 08:08 UTC
Allow reconfiguration to switch between networks (mainnet, testnet and regtest) at any time (only intended for devs, not users).

**Comment by olafmarcos** [comment] 2020-12-11 12:00
Hi @mayankchhabra, why this feature is not intendend for users? I would like to switch my installation form testnet to mainnet without making all the installation again.

Regards,

**Comment by mayankchhabra** [comment] 2020-12-11 14:49
Great question, @olafmarcos!

One of the things that we're very religious about is abstracting as much complexity as possible, and exposing as little configuration options as possible. We strive to set the best possible configuration options by default to make stuff "just work" without any user intervention. All feature requests are carefully vetted, and a feature is only implemented after we are sure that it will make lives better for at least 80% of our users.

If not, the idea is dropped — even if we personally like it and have our own biases. We want to be careful with the opportunity costs at all times, making sure that we're only working on things that have high impact. Spending time and effort on implementing something that would help a minority of users means **not** spending time and effort on something that could help the majority of users.

Re this specific feature, most users don't know the differences between testnet, regtest and mainnet because the first two networks are only used by developers. There could be times where advanced users, such as yourself, would like to play around without risking real money. In that case (because these users are quite technical), there's nothing stopping them from SSHing into their Umbrel and re-running the configuration script to switch to a different network.

**Comment by olafmarcos** [comment] 2020-12-13 21:17
Totally agree @mayankchhabra that things should running as smoothly as possible for most users.

But i'm pulling my hair on how to change the installation to mainnet.

I tried:

- Re-running the ./configure script (with and without the NETWORK parameter) "sudo NETWORK=mainnet ./scripts/configure"
- Remove the bitcoin/bitcoinf.conf file as it contains these two lines in the begin and rerun the configure script:
testnet=1
[test]
- Review the templates/bitcoin.conf file but it doesn't contain any line with "testnet" sentences.

As i do not find any bitcoind.conf file in the umbrel path i'm a bit lost.

I'm in a Linux/Debian installation. I don't know if this can cause any conflict with the "configure" script and not work as intended.

Would it be an idea to include a section (may be hidden) to these "advanced user" features?

Thank you in advance.

Kind regards,

**Comment by mayankchhabra** [comment] 2020-12-14 15:45
@olafmarcos Sorry it's not supported out-of-the-box right now which is why this issue has been opened.

Meanwhile, can you please try setting `BITCOIN_NETWORK=mainnet` in the `.env` file of your Umbrel installation directory? 

Then run `sudo ./scripts/configure` and see if that helps.

Also, is there a particular reason why you'd like to reconfigure your current Umbrel installation instead of deleting it and starting afresh on mainnet?

**Comment by olafmarcos** [comment] 2020-12-14 20:16
Progressing...

`./bin/bitcoin-cli -getinfo
{
  "version": 200100,
  "blocks": 135617,
  "headers": 661374,
  "verificationprogress": 0.001687984942238737,
  "timeoffset": 0,
  "connections": 4,
  "proxy": "10.11.5.1:29050",
  "difficulty": 1563027.996116223,
  "chain": "main",
  "balance": 0.00000000,
  "keypoolsize": 1000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "warnings": ""
}
`
After changing the setting in `.env` (it contained testnet), the running instance has changed but i get an error after login in the dashboard:
`Unable to unlock wallet, wallet not found`

I suppose this is normal because i only have a wallet in testnet environment. Is there any CLI command to make a wallet in the new umbrel mainnet environment?

I would like to mantain the testnet environment to try things without compromise the real wallet.

Probably it is easier to install a parallel installation in other path, but i was experimenting in order to not mantain two different installations.

Thanks a lot..

**Comment by mayankchhabra** [comment] 2020-12-15 14:02
Ah sorry about that, just realized that it wouldn't be possible to switch without deleting a few database files, which could get really messy and awkward when trying to switch back to testnet. I'd recommend waiting for this feature to be implemented.

Meanwhile, parallel installations would be your best bet. Two different installations wouldn't have any overhead (except the Bitcoin blockchain data, which would be the same in case of a single installation as well) since they'd use the same Docker images.

**Comment by olafmarcos** [comment] 2020-12-15 18:07
Ok, no problem...

I keep on pending to test the feature when available...

Kind regards,

**Comment by danielcharrua** [comment] 2022-05-08 18:36
Hello @mayankchhabra, any updates on this issue? This will be implemented in a near or far future? Thank you

**Comment by nmfretz** [comment] 2023-05-26 23:39
Closed by https://github.com/getumbrel/umbrel-bitcoin/commit/cc5e1fd98dd682bf7e5464a4298cdffe27af6eea

**Closed by nmfretz** 2023-05-26 23:39 UTC
Labels: feature
