### ISSUE TITLE
Integrate ION, the 'Layer 2' overlay for Decentralized Identifier (DID) 

### ISSUE THREAD

**Issue by zernaIO** [getumbrel/umbrel#648] opened 2021-03-16 20:20 UTC
Hello and a good evening to all,

I would love it if ION could be integrated with Umbrel. I really don't know if this will be possible at all. So I just put this here for discussion.  So this whole issue can be viewed as a feature request.
Decentralized Identifiers are an important part of the "Web of Trusts" and enable Self Sovereign Identities (SSI). Which are important in their own right, so that claims about entities (people, machines, and so on) can be verified and issued independently of middlemen.

ION is based on the blockchain agnostic "Sidetree Protocol" and is the integration for bitcoin.  ION also offers a way to run all the services you need over Docker. As you can see from the [docker-compose file](https://github.com/decentralized-identity/ion/blob/master/docker/docker-compose.yml).

I just put this here for discussion. I am curious about your opinions. I hope to be able to work on this myself, as I could also familiarize myself with Umbrel app development.

**References**
[Wikipedia: Decentralized Identifier](https://en.wikipedia.org/wiki/Decentralized_identifiers)
[Wikipedia: SSI](https://en.wikipedia.org/wiki/Self-sovereign_identity)
[W3C Working Draft for Decentralized Identifier](https://www.w3.org/TR/did-core/)
[ION Repo](https://github.com/decentralized-identity/ion)
[Sidetree Repo](https://github.com/decentralized-identity/sidetree)

**Comment by AaronDewes** [comment] 2021-03-17 06:22
Duplicate of #560

**Comment by zernaIO** [comment] 2021-03-17 08:02
HI @AaronDewes, sorry for that duplicate! Should I close my issue and attach my info to the original, or should we stay with this one, because of more detailed information?

**Comment by AaronDewes** [comment] 2021-03-17 14:50
Please attach your information to the original issue.

**Closed** 2021-03-17 16:30 UTC
