### ISSUE TITLE
RTL won't start after updating to 0.4.8

### ISSUE THREAD

**Issue by moonsettler** [getumbrel/umbrel#1112] opened 2021-11-16 14:36 UTC
first installed update over web ui, RTL says starting but nothing can be reached on port 3001
tried to:
- uninstall RTL reinstall
- stop, manually update umbrel with curl, start
- stop, docker container prune, docker image prune, start

same symptoms

**Comment by moonsettler** [comment] 2021-11-16 15:06
also tried manually overwriting the files from the tar, nothing
finally tried overwriting the files with the 0.4.7 tar and RTL started without issues.

**Comment by metasikander** [comment] 2021-11-16 16:51
did you check the logs for that container?
i have issues with it too, but i get `env: can't execute 'bash': No such file or directory` in the logs.

**Comment by moonsettler** [comment] 2021-11-16 16:53
probably checked the wrong logs because they told me nothing. lemme try it on testnet...

**Comment by moonsettler** [comment] 2021-11-16 17:16
this is what i got in shell after start:
`Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/data/entrypoint.sh": stat /data/entrypoint.sh: no such file or directory: unknown`

generating logs:
`Error: Failed to fetch debug data.`

**Comment by tcdo6666** [comment] 2021-11-18 04:30
Same, logs show:
`web_1   | env: can't execute 'bash': No such file or directory`

**Comment by tcdo6666** [comment] 2021-11-18 04:40
Reverted to 0.4.7 and RTL installed and started.

**Comment by metasikander** [comment] 2021-11-18 09:26
same here.
makes me think the issue is here:
https://github.com/getumbrel/umbrel/blob/master/apps/ride-the-lightning/rtl/entrypoint.sh#L1

the rtl container doesn't have bash, so i think it should be sh instead.

**Comment by louneskmt** [comment] 2021-11-18 11:06
Hey guys, do you run UmbrelOS on Pi or Umbrel on a Linux-based system?

**Comment by metasikander** [comment] 2021-11-18 11:08
i run mine on ubuntu in a x86 vm

**Comment by moonsettler** [comment] 2021-11-18 12:22
debian 11 vm for me

**Comment by louneskmt** [comment] 2021-11-18 13:47
All the users reporting this issue are running Umbrel not on ARM64 (so not on Pi). 

I think the issue is that the RTL image for amd64 doesn't contain bash. This will likely be fixed in the next Umbrel version.

**Closed** 2021-11-22 12:45 UTC

**Comment by johnkeong** [comment] 2021-11-23 11:17
Hi I'm having issue about RTL stuck at "starting". Running on Dell Latitude E6440 Ubuntu 20.04.3 LTS (Focal Fossa).

Attached is the link to my post in Umbrel Community's page: https://community.getumbrel.com/t/rtl-stuck-after-install/4821

**Comment by AndreasAtakan** [comment] 2021-11-23 16:36
I'm also having the same issue as described by @moonsettler , @metasikander and @tcdo6666 .
I'm running Umbrel on Debian 11 x86 installed on an old desktop PC (not a VM).

**Comment by louneskmt** [comment] 2021-11-23 18:01
@AndreasAtakan The fix has been merged and will be included in the next Umbrel release. For now, please check https://community.getumbrel.com/t/ride-the-lightning-stuck-in-starting-loop/4730/11?u=louneskmt.
